### PR TITLE
Added support for CSR1000v in topomachine

### PR DESCRIPTION
**Pull request by emjemj**
Basic support for CSR1000v in topomachine, ugly hack for weird interface mappings, this is probably something that can easily be improved upon.

### CODE REVIEW

**Comment by plajjan** [comment]
I don't want that remapping done here.. if we're going to do a hack it belongs in the csr1000v launch script. Fix that separately please.

**Comment by emjemj** [comment]
I assumed that the documentation was not correct but when I tested they are in order when I tested so I have removed the interface remapping hack.

**Comment by plajjan** [comment]
Too many negations? Please update csr1kv docs with what version you tested with. I suspect it might be differences between versions.

**Comment by emjemj** [comment]
Yes, obviously too many negations. I will update the docs.

**Comment by plajjan** [comment]
LGTM

**Pull request merged**
