### PR TITLE
vEOS requires it's ma1 interface to be the first interface in the bus

### LINKED ISSUE #160: vrssh fails for vEOS VRs
```
(vrnetlab-venv) benm@benm-laptop:~/venvs/vrnetlab-venv/vrnetlab$ vrssh vr3
ssh_exchange_identification: Connection closed by remote host
```

### PR DESCRIPTION
**Pull request by grahamneville**
Attempting to fix #160.

I've tested my code against 2 lots of vEOS versions and also a CSR to ensure that still works

### CODE REVIEW

**Comment by plajjan** [comment]
So without this patch, which interface is first on the bus? Do you have a full output from `ps` or something? I thought mgmt was the first one already.

**Comment by mirceaulinic** [comment]
I also had some issues with very new vEOS images: I was able to telnet but could not SSH although the management interface looked correctly configured.
I will try to spawn them again soon and come back with more details if needed.

**Comment by htj** [comment]
I can confirm that SSH does not work without this patch, and that it works with it.

+1 for merging.

**Comment by mirceaulinic** [comment]
I have finally tested these changes, and I also confirm that it doesn't work without them. Thanks @grahamneville.

**Comment by viniciusarcanjo** [comment]
Thanks @grahamneville! I've also confirmed that on 4.20.1F it works.

@plajjan Can we have this patch merged?

**Comment by htj** [comment]
@emjemj Since you have the merge/push keys. Pretty please.

**Comment by emjemj** [comment]
If you say so, I'm not able to test myself unfortunately.

**Comment by htj** [comment]
Thank you.

**Pull request merged**
