### PR TITLE
csr: Added support to load a license file

### PR DESCRIPTION
**Pull request by fredsod**
There is a 100kbit/s throughput limit on CSR1000v. This PR adds support to load a license file to unlock more bandwidth.

### CODE REVIEW

**Comment by plajjan** [comment]
For SROS I adapted a different naming format for the license file which makes it easy to support a license file per image, see https://github.com/plajjan/vrnetlab/tree/master/sros#license-handling. Is this applicable for CSR? Can you have a different license file per image? I think it's nice that I can have multiple image files in the sros dir and it will build a docker image per source image automagically... with the matching license file.

**Comment by fredsod** [comment]
Oh, that looks nice. I'll open a new PR.

**Comment by hex2a** [comment]
Is there a way to extract the (v)UDI for which the license needs to be generated?

**Comment by plajjan** [comment]
Dunno but that would be part of the CSR and not really vrnetlab so check the CSR docs?

**Comment by hex2a** [comment]
according to the CSR docs:
> When you clone the Cisco CSR 1000v, you will automatically get a new vUDI, and all the licenses from the original VM should be removed.

Not sure if/how building an image works under these circumstances?

**Comment by plajjan** [comment]
Hmm ,right. I dunno. @fredsod care to comment?

**Pull request closed without merging**
