### PR TITLE
add xrv9k support

### PR DESCRIPTION
**Pull request by bdreisbach**
initial attempt at xrv9k support.

### CODE REVIEW

**Comment by plajjan** [comment]
Thanks for your work! :)

How is this different from xrv ? I haven't looked at the detail but it doesn't stand out as very different - actually seems to align very well with the xrv stuff. Would it be possible to modify the xrv image instead of creating a new one? This would likely minimise maintenance of this.. :)

**Comment by bdreisbach** [comment]
there are a few differences as i see it. im not sure if it can all be integrated into a single thing.

1. xrv9k ships with qcow2 vs vmdk. xrv launch script was hard coded to look for vmdk
2. xrv9k requires different cpu configuration than xrv
3. xrv9k has 4 serial ports vs 1 on xrv
4. xrv9k mgmt interface name is different than xrv
5. xrv9k requires 2 dummy interfaces
6. slight subtleties in the bootstrap configuration

**Comment by plajjan** [comment]
Closing this since we now have xrv9k support. It's based on your work and then slightly improved upon.

I think you also pushed commits here to use the docker API etc. I think that should be kept separate from the xrv9k work. Feel free to submit it separately :)

**Comment by plajjan** [comment]
And sorry for taking such time but it's a lot catching up on after parental leave ;)

**Pull request closed without merging**
