### PR TITLE
fix prefix support

### PR DESCRIPTION
**Pull request by bdreisbach**
prefix support is broken, this patch fixes it.
i've been using this fix for some time now, so its been tested somewhat.

### CODE REVIEW

**Comment by emjemj** [comment]
@plajjan looks resonable, merge?

**Comment by plajjan** [comment]
@emjemj didn't I grant you push access? I'm on parental leave so lag++ ;) please merge stuff that looks good :)

**Comment by emjemj** [comment]
@plajjan Yeah, you did. :)

**Comment by emjemj** [comment]
Looks good :)

**Pull request merged**
